import { Dancing_Script, Inter } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import { ScrollArea } from "@/components/ui/scroll-area";
import { MainNav } from "@/components/Navbar/Main_Nav";
import NextTopLoader from "nextjs-toploader";
import Footer from "@/components/HomePage/Footer/Footer";
import StoreProvider from "./StoreProvider";

const inter = Inter({
  variable: "--font-inter", // Use the variable you want
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Beach Bar and Lodge",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/new_logo/Logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <StoreProvider>
          <ScrollArea className="h-[100vh]">
            <MainNav />
            <NextTopLoader color="#fdfefc" showSpinner={false} />
            {children}
            <Footer />
          </ScrollArea>
        </StoreProvider>
      </body>
    </html>
  );
}
